# Default values for cnp-sandbox.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#
# Copyright 2021 EnterpriseDB Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# -- here you can pass the whole values directly to the kube-prometheus-stack chart
kube-prometheus-stack:
  enabled: true
  prometheus:
    prometheusSpec:
      podMonitorSelectorNilUsesHelmValues: false
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false
  grafana:
    enabled: true
    # -- the grafana admin password
    adminPassword: prom-operator
  alertmanager:
    enabled: false


# -- here you can pass the whole values directly to the cloud-native-postgresql chart
cloud-native-postgresql:
  enabled: true
  config:
    create: true
    data:
      MONITORING_QUERIES_CONFIGMAP: default-monitoring-queries
