{{- if .Values.defaultAlerts }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}-default-alerts
  labels:
    {{- include "cnp-sandbox.labels" . | nindent 4 }}
spec:
{{ .Files.Get "alerts.yaml" | indent 2 }}
{{- end }}
