name: continuous-delivery

on:
  pull_request:

jobs:
  install_deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v2.0
        with:
          version: v3.7.1

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0

      - name: Deploy using helm chart
        run: |
          helm dependency update charts/cnp-sandbox
          helm upgrade --install --set dependenciesOnly=true cnp-sandbox charts/cnp-sandbox --wait --atomic
          helm upgrade --install --set dependenciesOnly=false cnp-sandbox charts/cnp-sandbox --wait --atomic
