name: linter

on:
  push:
    branches:
      - '**'
      - '!gh-pages'

jobs:
  linter:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3.3
        with:
          version: v3.7.1

      - uses: actions/setup-python@v3
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch=main)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Run chart-testing (lint)
        run: |
          helm dependency update charts/cnp-sandbox
          helm repo add cnp https://enterprisedb.github.io/cloud-native-postgresql-helm/
          helm repo add prometheus https://prometheus-community.github.io/helm-charts
          ct lint --target-branch=main --check-version-increment=false
