name: sonarqube
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:

  duplicate_runs:
    runs-on: ubuntu-20.04
    name: Skip duplicate runs
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v3.4.1
        with:
          concurrent_skipping: 'same_content'
          skip_after_successful_duplicate: 'true'
          paths_ignore: '["README.md", "docs/**"]'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

  sonarqube-scan:
    name: SonarQube Scan
    needs: duplicate_runs
    if: ${{ needs.duplicate_runs.outputs.should_skip != 'true' }}
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2.4.0
      -
        name: Checkout EDB GitHub Actions Repo
        uses: actions/checkout@v2.4.0
        with:
          repository: EnterpriseDB/edb-github-actions.git
          ref: master # wokeignore:rule=master
          token: ${{ secrets.GH_API_TOKEN }}
          path: .github/actions/edb-github-actions
      -
        name: SonarQube Scan
        uses: ./.github/actions/edb-github-actions/sonarqube
        with:
          REPO_NAME: '${{ github.event.repository.name }}'
          SONAR_PROJECT_KEY: '${{ secrets.SONARQUBE_PROJECTKEY }}'
          SONAR_URL: '${{ secrets.SONARQUBE_URL }}'
          SONAR_LOGIN: '${{ secrets.SONARQUBE_LOGIN }}'
          PULL_REQUEST_KEY: '${{ github.event.number }}'
          PULL_REQUEST_BRANCH: '${{ github.head_ref }}'
          PULL_REQUEST_BASE_BRANCH: '${{ github.base_ref }}'
          REPO_DEFAULT_BRANCH: '${{ github.event.repository.default_branch }}'
          REPO_EXCLUDE_FILES: '**/*_test.go,**/*.md,**/*.txt,**/*.yaml,**/*.yml,**/*.template,**/*.json,**/*.csv'
